# Generated by Django 4.2.8 on 2023-12-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='Sitedescription',
        ),
    ]
