# Generated by Django 4.2.8 on 2023-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_globalsettings_sitedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='SiteRegister',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='Sitelicence',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='broc_name',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='brochure',
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='logo',
            field=models.ImageField(default=None, max_length=200, null=True, upload_to='Logo/'),
        ),
    ]
