# Generated by Django 4.2.8 on 2023-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_remove_globalsettings_siteregister_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='scanner',
            field=models.ImageField(null=True, upload_to='QR'),
        ),
    ]
