# Generated by Django 4.2.8 on 2023-12-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_globalsettings_scanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='Whatsapp',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
