# Generated by Django 4.2.8 on 2023-12-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Slider', 'Home/Slider'), ('Home/Aboutus', 'Home/Aboutus'), ('Apply/Slider', 'Apply/Slider'), ('Home/CompanyData', 'Home/CompanyData'), ('CompanyData/Slider', 'CompanyData/Slider'), ('CompanyData Details', 'CompanyData Details'), ('M&V/Slider', 'M&V/Slider'), ('Mission & Vision', 'Mission & Vision'), ('Testimonial', 'Testimonial'), ('Testimonial/Background', 'Testimonial/Background'), ('Clients', 'Clients'), ('AboutUs', 'AboutUs'), ('About/WhoWeAre', 'About/WhoWeAre'), ('WhoWeAre/Slider', 'WhoWeAre/Slider'), ('WhyChoose Us/Qualities', 'WhyChoose Us/Qualities'), ('WhyChooseUs', 'WhyChooseUs'), ('WhyChooseUs/Slider', 'WhyChooseUs/Slider'), ('Gallery', 'Gallery'), ('Gallery/slider', 'Gallery/slider'), ('Gallery/Company profile', 'Gallery/Company profile'), ('Gallery/Events', 'Gallery/Events'), ('Contact us', 'contact us')], max_length=50, null=True),
        ),
    ]
