# Generated by Django 4.2.8 on 2023-12-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='video',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
