# Generated by Django 4.2.8 on 2023-12-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Slider', 'Home/Slider'), ('Home/Aboutus', 'Home/Aboutus'), ('Apply/Slider', 'Apply/Slider'), ('Home/CompanyData', 'Home/CompanyData'), ('CompanyData/Slider', 'CompanyData/Slider'), ('CompanyData Details', 'CompanyData Details'), ('M&V/Slider', 'M&V/Slider'), ('Mission & Vision', 'Mission & Vision'), ('Testimonial', 'Testimonial'), ('Testimonial/Background', 'Testimonial/Background'), ('Clients', 'Clients'), ('AboutUs', 'AboutUs'), ('About/WhoWeAre', 'About/WhoWeAre'), ('WhoWeAre/Slider', 'WhoWeAre/Slider'), ('WhyChoose Us/Qualities', 'WhyChoose Us/Qualities'), ('WhyChooseUs', 'WhyChooseUs'), ('WhyChooseUs/Slider', 'WhyChooseUs/Slider'), ('Image Gallery', 'Image Gallery'), ('Image Gallery/slider', 'Image Gallery/slider'), ('order Product', 'order Product'), ('Video Gallery', 'Video Gallery'), ('Video Gallery/slider', 'Video Gallery/slider'), ('Product', 'Product'), ('Product/slider', 'Product/slider'), ('Contact us', 'contact us')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('sub_category', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=50)),
                ('position', models.IntegerField()),
                ('page_type', models.CharField(blank=True, choices=[('Product Details', 'Product Details')], max_length=50, null=True)),
                ('product_desc', models.CharField(max_length=200)),
                ('key_features', models.TextField(null=True)),
                ('Specification', models.TextField(null=True)),
                ('productimage', models.ImageField(null=True, upload_to='ProductImage/')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='adminpanel.product')),
            ],
        ),
    ]
