# Generated by Django 4.2.8 on 2023-12-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0022_alter_navigation_page_type_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Specification',
            new_name='specification',
        ),
    ]
