# Generated by Django 4.2.8 on 2023-12-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0023_rename_specification_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Normal', 'Normal'), ('Home', 'Home'), ('Home/Slider', 'Home/Slider'), ('Home/Aboutus', 'Home/Aboutus'), ('Apply/Slider', 'Apply/Slider'), ('Home/CompanyData', 'Home/CompanyData'), ('CompanyData/Slider', 'CompanyData/Slider'), ('CompanyData Details', 'CompanyData Details'), ('M&V/Slider', 'M&V/Slider'), ('Mission & Vision', 'Mission & Vision'), ('Testimonial', 'Testimonial'), ('Testimonial/Background', 'Testimonial/Background'), ('Clients', 'Clients'), ('AboutUs', 'AboutUs'), ('About/WhoWeAre', 'About/WhoWeAre'), ('WhoWeAre/Slider', 'WhoWeAre/Slider'), ('WhyChoose Us/Qualities', 'WhyChoose Us/Qualities'), ('WhyChooseUs', 'WhyChooseUs'), ('WhyChooseUs/Slider', 'WhyChooseUs/Slider'), ('Image Gallery', 'Image Gallery'), ('Image Gallery/slider', 'Image Gallery/slider'), ('order Product', 'order Product'), ('Video Gallery', 'Video Gallery'), ('Video Gallery/slider', 'Video Gallery/slider'), ('Product', 'Product'), ('Product/slider', 'Product/slider'), ('Contact us', 'contact us')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Group', 'Group'), ('Normal', 'Normal'), ('Product Details', 'Product Details')], max_length=50, null=True),
        ),
    ]
