# Generated by Django 4.2.8 on 2023-12-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0024_alter_navigation_page_type_alter_product_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
